version: '3'

services:
  bench_nginx:
    image: nginx:1.12.2-alpine
    volumes:
      - ./fixtures:/usr/share/nginx/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    expose:
      - 80
    ports:
      - "8989:80"

  benchmark:
    build: .
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    working_dir: /usr/app/
    environment:
      NGINX: bench_nginx
    depends_on:
      - bench_nginx
    links:
      - bench_nginx
